version: '2'

services: 
  graphana:
    image: grafana/grafana
  mongo:
    image: mongo
  mongo-accessor:
    build: 
      context: ./vertx-demo-mongo-accessor
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
      - MONGO_HOST=$MONGO_HOST
  calculator:
    build: 
      context: ./vertx-demo-calculator
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
  server-with-jmx:
    build: 
      context: ./vertx-demo-server-with-jmx
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
  server-with-hawk:
    build: 
      context: ./vertx-demo-server-with-hawkular
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
      - HAWKULAR_HOST=172.30.30.64
      - HAWKULAR_PORT=8080