version: '2'

services: 
  graphana:
    image: grafana/grafana
  mongo:
    image: mongo
  mongo-accessor:
    build: 
      context: ./vertx-demo-mongo-accessor
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
      - MONGO_HOST=$MONGO_HOST
  calculator:
    ports:
      - 4003:4000
      - 5703:5701
    build: 
      context: ./vertx-demo-calculator
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
      - CLUSTER_IFACE=eth0
      - CLUSTER_PUBLIC_PORT=4003
      - VERTX_PORT=5701
  server-xml:
    ports:
      - 4002:4000
      - 5704:5701
      - 8081:8080
    build: 
      context: ./vertx-server-xml-config
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
      - CLUSTER_IFACE=eth0
      - CLUSTER_PUBLIC_PORT=4002
      - VERTX_PORT=5701
  server-with-hawk:
    build: 
      context: ./vertx-demo-server-with-hawkular
      dockerfile: Dockerfile
    environment:
      - CLUSTER_JOIN=$CLUSTER_MASTER
      - HAWKULAR_HOST=172.30.30.64
      - HAWKULAR_PORT=8080