app:
 build: .
 dockerfile: AppDockerfile
 links:
  - mysql:mysql
 expose:
  - "8080"
www:
 build: .
 dockerfile: WwwDockerfile
 links:
  - app:app
 ports:
  - "8080:8080"
mysql:
 image: mysql
 container_name: mysql
 environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=hibernate
