#!/bin/bash

CONTAINER_STRING="$1"
CONSUL_IP="$2"
REGISTRATOR_NAME="consul-registrator"

if [[ -z $CONTAINER_STRING ]]; then
	echo "Please provide container name string as first parameter..."
	exit 1
fi

if [[ -z $CONSUL_IP ]]; then
	echo "Please provide proper consul server ip address as second parameter..."
	exit 2
fi

CONTAINER_LIST=$(docker-machine ls -q | grep $CONTAINER_STRING)

for c in $CONTAINER_LIST; do
	eval $(docker-machine env $c)
	if [[ 1 -eq $(docker ps -a --format={{.Names}} | grep $REGISTRATOR_NAME -c) ]]; then
		echo "Stopping and removing existing consul registrator running container"
		docker kill $REGISTRATOR_NAME
		docker rm $REGISTRATOR_NAME
	fi
	docker run -d --name $REGISTRATOR_NAME -v /var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator consul://$CONSUL_IP
done